CREATE TABLE IF NOT EXISTS LOGIN (
    USERNAME TEXT PRIMARY KEY NOT NULL,
    PASSWORD TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS PATH (
    URI TEXT PRIMARY KEY NOT NULL
)

CREATE TABLE IF NOT EXISTS PASSWORDS (
    SERVICE TEXT PRIMARY KEY NOT NULL,
    PASSWORD TEXT NOT NULL,
    LAST_UPDATE TEXT NOT NULL
)